# This is a basic workflow to help you get started with Actions

name: CI deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  repository_dispatch:
    types:
      - deploy_dev_page
  workflow_dispatch: 


jobs:
  deploy-page:
    runs-on: ubuntu-22.04

    steps:
      - name: Clone pages
        run: git clone https://github.com/rfblock/qalculate-nb.git && cd qalculate-nb; git checkout gh-pages-dev; rm -rf .git/

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          fqdn: dev.qalc.steg.gy
          target_branch: gh-pages
          build_dir: qalculate-nb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
